name: Continous Integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout Repository
      - uses: actions/checkout@v3

       # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
          

      # Install Dependencies
      - name: installing dependencies
        run: composer install --prefer-dist --no-progress --no-suggest


      - name: run install, build and test
        run: |
          composer install
          sudo chmod -R 777 vendor/
          vendor/bin/phpunit Tests




