name: Continous Integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      # Install PHPStan
      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan
          
      # Install Dependencies
      - name: installing dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit Tests

      # Run PHPStan tests
      - name: Run PHPStan tests
        run: vendor/bin/phpstan analyse Src Tests



